# builtins.pyi — چیت‌شیت توابع داخلی پایتون
from typing import Any, Iterable, Union, Optional, Callable, TypeVar, overload, Generic

T = TypeVar("T")
K = TypeVar("K")
V = TypeVar("V")

# ============================================================
# print
# ============================================================
def print(
    *args: Any,
    sep: Optional[str] = ...,
    end: Optional[str] = ...,
    file: Any = ...,
    flush: bool = ...
) -> None:
    """
    📌 فرمول رایج:
    print("hello")
    print("name:", name)
    print("a", "b", "c", sep="-")

    📌 پارامترها:
    - *args: هر تعداد مقدار (با کاما جدا می‌شوند)
    - sep (اختیاری): جداکننده بین مقادیر — پیش‌فرض: فاصله (' ')
    - end (اختیاری): انتهای خروجی — پیش‌فرض: خط جدید ('\n')
    - file (اختیاری): خروجی به فایل
    - flush (اختیاری): فلاش کردن بافر
    """
    ...

# ============================================================
# ord / chr
# ============================================================
def ord(c: str) -> int:
    """
    📌 فرمول رایج:
    ord('q')        ← 113
    ord('a')        ← 97

    📌 پارامترها:
    - c: یک کاراکتر (رشته تک‌حرفی)

    📌 برمی‌گردونه: کد ASCII/Unicode کاراکتر

    📌 کاربرد رایج در OpenCV:
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    """
    ...

def chr(i: int) -> str:
    """
    📌 فرمول رایج:
    chr(113)        ← 'q'
    chr(97)         ← 'a'

    📌 پارامترها:
    - i: کد ASCII/Unicode

    📌 برمی‌گردونه: کاراکتر مربوط به کد
    """
    ...

# ============================================================
# type (به عنوان کلاس)
# ============================================================
class type:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __name__(self) -> str: ...
    def __qualname__(self) -> str: ...
    def __module__(self) -> str: ...
    def __bases__(self) -> tuple: ...
    def __mro__(self) -> tuple: ...
    def __subclasses__(self) -> list: ...
    def __instancecheck__(self, instance: Any) -> bool: ...
    def __subclasscheck__(self, subclass: Any) -> bool: ...

# ============================================================
# property decorator
# ============================================================
class property:
    def __init__(
        self,
        fget: Optional[Callable] = ...,
        fset: Optional[Callable] = ...,
        fdel: Optional[Callable] = ...,
        doc: Optional[str] = ...,
    ) -> None: ...
    def getter(self, fget: Callable) -> property: ...
    def setter(self, fset: Callable) -> property: ...
    def deleter(self, fdel: Callable) -> property: ...
    def __get__(self, obj: Any, objtype: Any = ...) -> Any: ...
    def __set__(self, obj: Any, value: Any) -> None: ...
    def __delete__(self, obj: Any) -> None: ...

# ============================================================
# staticmethod decorator
# ============================================================
class staticmethod:
    def __init__(self, f: Callable) -> None: ...
    def __get__(self, obj: Any, objtype: Any = ...) -> Any: ...

# ============================================================
# classmethod decorator
# ============================================================
class classmethod:
    def __init__(self, f: Callable) -> None: ...
    def __get__(self, obj: Any, objtype: Any = ...) -> Any: ...

# ============================================================
# Exception classes
# ============================================================
class BaseException:
    def __init__(self, *args: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def with_traceback(self, tb: Any) -> BaseException: ...
    @property
    def args(self) -> tuple: ...
    @property
    def __traceback__(self) -> Any: ...

class Exception(BaseException):
    def __init__(self, *args: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ValueError(Exception):
    def __init__(self, *args: Any) -> None: ...

class TypeError(Exception):
    def __init__(self, *args: Any) -> None: ...

class KeyError(Exception):
    def __init__(self, *args: Any) -> None: ...

class IndexError(Exception):
    def __init__(self, *args: Any) -> None: ...

class AttributeError(Exception):
    def __init__(self, *args: Any) -> None: ...

class ImportError(Exception):
    def __init__(self, *args: Any) -> None: ...

class FileNotFoundError(Exception):
    def __init__(self, *args: Any) -> None: ...

class IOError(Exception):
    def __init__(self, *args: Any) -> None: ...

class RuntimeError(Exception):
    def __init__(self, *args: Any) -> None: ...

class ZeroDivisionError(Exception):
    def __init__(self, *args: Any) -> None: ...

class NameError(Exception):
    def __init__(self, *args: Any) -> None: ...

class StopIteration(Exception):
    def __init__(self, *args: Any) -> None: ...

class KeyboardInterrupt(BaseException):
    def __init__(self, *args: Any) -> None: ...

class SystemExit(BaseException):
    def __init__(self, *args: Any) -> None: ...

# ============================================================
# کلاس‌های پایه (base types)
# ============================================================
class object:
    def __init__(self) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __format__(self, format_spec: str) -> str: ...
    def __sizeof__(self) -> int: ...
    def __reduce__(self) -> Any: ...
    def __reduce_ex__(self, protocol: int) -> Any: ...
    def __dir__(self) -> list: ...
    def __init_subclass__(cls) -> None: ...

class int:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: Union[str, float, int, bool, bytes]) -> None: ...
    @overload
    def __init__(self, x: str, base: int) -> None: ...
    # Arithmetic operators
    def __add__(self, other: Any) -> int: ...
    def __sub__(self, other: Any) -> int: ...
    def __mul__(self, other: Any) -> int: ...
    def __truediv__(self, other: Any) -> float: ...
    def __floordiv__(self, other: Any) -> int: ...
    def __mod__(self, other: Any) -> int: ...
    def __pow__(self, other: Any) -> int: ...
    def __neg__(self) -> int: ...
    def __pos__(self) -> int: ...
    def __abs__(self) -> int: ...
    def __invert__(self) -> int: ...
    # Bitwise operators
    def __and__(self, other: Any) -> int: ...
    def __or__(self, other: Any) -> int: ...
    def __xor__(self, other: Any) -> int: ...
    def __lshift__(self, other: Any) -> int: ...
    def __rshift__(self, other: Any) -> int: ...
    # Comparison operators
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    # Type conversion
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    # Methods
    def bit_length(self) -> int: ...
    def to_bytes(self, length: int, byteorder: str, *, signed: bool = ...) -> bytes: ...

class float:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: Union[str, float, int, bool]) -> None: ...
    # Arithmetic operators
    def __add__(self, other: Any) -> float: ...
    def __sub__(self, other: Any) -> float: ...
    def __mul__(self, other: Any) -> float: ...
    def __truediv__(self, other: Any) -> float: ...
    def __floordiv__(self, other: Any) -> float: ...
    def __mod__(self, other: Any) -> float: ...
    def __pow__(self, other: Any) -> float: ...
    def __neg__(self) -> float: ...
    def __pos__(self) -> float: ...
    def __abs__(self) -> float: ...
    # Comparison operators
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    # Type conversion
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    # Methods
    def is_integer(self) -> bool: ...
    def hex(self) -> str: ...

class complex:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, real: float, imag: float = ...) -> None: ...
    @overload
    def __init__(self, real: str) -> None: ...
    def real(self) -> float: ...
    def imag(self) -> float: ...
    def conjugate(self) -> complex: ...
    def __add__(self, other: Any) -> complex: ...
    def __sub__(self, other: Any) -> complex: ...
    def __mul__(self, other: Any) -> complex: ...
    def __truediv__(self, other: Any) -> complex: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __abs__(self) -> float: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

class bytes:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, int_value: int) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[int]) -> None: ...
    @overload
    def __init__(self, string: str, encoding: str = ..., errors: str = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: Union[int, slice]) -> Union[int, bytes]: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: Union[int, bytes]) -> bool: ...
    def __add__(self, other: bytes) -> bytes: ...
    def __mul__(self, other: int) -> bytes: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: bytes) -> bool: ...
    def __le__(self, other: bytes) -> bool: ...
    def __gt__(self, other: bytes) -> bool: ...
    def __ge__(self, other: bytes) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def decode(self, encoding: str = ..., errors: str = ...) -> str: ...
    def hex(self) -> str: ...
    @classmethod
    def fromhex(cls, string: str) -> bytes: ...
    def join(self, iterable: Iterable[bytes]) -> bytes: ...
    def split(self, sep: Optional[bytes] = ..., maxsplit: int = ...) -> list: ...
    def rsplit(self, sep: Optional[bytes] = ..., maxsplit: int = ...) -> list: ...
    def startswith(self, prefix: Union[bytes, tuple]) -> bool: ...
    def endswith(self, suffix: Union[bytes, tuple]) -> bool: ...
    def find(self, sub: bytes, start: int = ..., end: int = ...) -> int: ...
    def rfind(self, sub: bytes, start: int = ..., end: int = ...) -> int: ...
    def count(self, sub: bytes, start: int = ..., end: int = ...) -> int: ...
    def replace(self, old: bytes, new: bytes, count: int = ...) -> bytes: ...
    def strip(self, chars: Optional[bytes] = ...) -> bytes: ...
    def lstrip(self, chars: Optional[bytes] = ...) -> bytes: ...
    def rstrip(self, chars: Optional[bytes] = ...) -> bytes: ...
    def upper(self) -> bytes: ...
    def lower(self) -> bytes: ...
    def title(self) -> bytes: ...
    def capitalize(self) -> bytes: ...

class slice:
    @overload
    def __init__(self, stop: int) -> None: ...
    @overload
    def __init__(
        self, start: Optional[int], stop: Optional[int], step: Optional[int] = ...
    ) -> None: ...
    def start(self) -> Optional[int]: ...
    def stop(self) -> Optional[int]: ...
    def step(self) -> Optional[int]: ...
    def indices(self, len: int) -> tuple: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class str:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: Any) -> None: ...
    @overload
    def __init__(self, x: bytes, encoding: str = ..., errors: str = ...) -> None: ...
    def __add__(self, other: str) -> str: ...
    def __mul__(self, other: int) -> str: ...
    def __mod__(self, other: Any) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: str) -> bool: ...
    def __le__(self, other: str) -> bool: ...
    def __gt__(self, other: str) -> bool: ...
    def __ge__(self, other: str) -> bool: ...
    def __len__(self) -> int: ...
    def __contains__(self, other: str) -> bool: ...
    def __getitem__(self, index: Union[int, slice]) -> str: ...
    def __iter__(self) -> Any: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def encode(self, encoding: str = ..., errors: str = ...) -> bytes: ...
    def format(self, *args: Any, **kwargs: Any) -> str: ...
    def format_map(self, mapping: Any) -> str: ...
    def split(self, sep: Optional[str] = ..., maxsplit: int = ...) -> list: ...
    def rsplit(self, sep: Optional[str] = ..., maxsplit: int = ...) -> list: ...
    def splitlines(self, keepends: bool = ...) -> list: ...
    def strip(self, chars: Optional[str] = ...) -> str: ...
    def lstrip(self, chars: Optional[str] = ...) -> str: ...
    def rstrip(self, chars: Optional[str] = ...) -> str: ...
    def join(self, iterable: Iterable[str]) -> str: ...
    def replace(self, old: str, new: str, count: int = ...) -> str: ...
    def find(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def rfind(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def index(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def rindex(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def count(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def startswith(
        self, prefix: Union[str, tuple], start: int = ..., end: int = ...
    ) -> bool: ...
    def endswith(
        self, suffix: Union[str, tuple], start: int = ..., end: int = ...
    ) -> bool: ...
    def lower(self) -> str: ...
    def upper(self) -> str: ...
    def title(self) -> str: ...
    def capitalize(self) -> str: ...
    def casefold(self) -> str: ...
    def swapcase(self) -> str: ...
    def center(self, width: int, fillchar: str = ...) -> str: ...
    def ljust(self, width: int, fillchar: str = ...) -> str: ...
    def rjust(self, width: int, fillchar: str = ...) -> str: ...
    def zfill(self, width: int) -> str: ...
    def isdigit(self) -> bool: ...
    def isalpha(self) -> bool: ...
    def isalnum(self) -> bool: ...
    def islower(self) -> bool: ...
    def isupper(self) -> bool: ...
    def isspace(self) -> bool: ...
    def isnumeric(self) -> bool: ...
    def isdecimal(self) -> bool: ...
    def isidentifier(self) -> bool: ...
    def isprintable(self) -> bool: ...
    def istitle(self) -> bool: ...
    def partition(self, sep: str) -> tuple: ...
    def rpartition(self, sep: str) -> tuple: ...
    def expandtabs(self, tabsize: int = ...) -> str: ...

class bool:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: Any) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __and__(self, other: Any) -> bool: ...
    def __or__(self, other: Any) -> bool: ...
    def __xor__(self, other: Any) -> bool: ...
    def __invert__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

# ============================================================
# len
# ============================================================
def len(obj: Any) -> int:
    """
    📌 فرمول رایج:
    len([1, 2, 3])      ← 3
    len("hello")        ← 5
    len({"a": 1})       ← 1

    📌 برمی‌گردونه: تعداد عناصر
    """
    ...

# ============================================================
# max / min / sum / sorted
# ============================================================
@overload
def max(
    iterable: Iterable[T],
    *,
    key: Optional[Callable[[T], Any]] = ...,
    default: Optional[T] = ...
) -> T: ...
@overload
def max(arg1: T, arg2: T, *args: T, key: Optional[Callable[[T], Any]] = ...) -> T: ...
def max(*args: Any, **kwargs: Any) -> Any:
    """
    📌 فرمول رایج:
    max([12, 6, 5, 2, 7])                    ← 12
    max(contours, key=cv2.contourArea)       ← بزرگترین کانتور
    max(contours, key=lambda c: cv2.contourArea(c))

    📌 پارامترها:
    - iterable: لیست/تاپل/مجموعه
    - key (اختیاری): تابع کلید برای تعیین معیار مقایسه
    - default (اختیاری): مقدار پیش‌فرض اگر iterable خالی باشد

    📌 برمی‌گردونه: بزرگترین مقدار (یا آیتم با بیشترین مقدار key)
    """
    ...

@overload
def min(
    iterable: Iterable[T],
    *,
    key: Optional[Callable[[T], Any]] = ...,
    default: Optional[T] = ...
) -> T: ...
@overload
def min(arg1: T, arg2: T, *args: T, key: Optional[Callable[[T], Any]] = ...) -> T: ...
def min(*args: Any, **kwargs: Any) -> Any:
    """
    📌 فرمول رایج:
    min([12, 6, 5, 2, 7])                    ← 2
    min(contours, key=cv2.contourArea)       ← کوچکترین کانتور

    📌 پارامترها:
    - iterable: لیست/تاپل/مجموعه
    - key (اختیاری): تابع کلید برای تعیین معیار مقایسه
    - default (اختیاری): مقدار پیش‌فرض اگر iterable خالی باشد

    📌 برمی‌گردونه: کوچکترین مقدار (یا آیتم با کمترین مقدار key)
    """
    ...

def sum(iterable: Iterable, start: Any = ...) -> Any:
    """
    📌 فرمول رایج:
    sum([12, 30, 40, 10])    ← 92

    📌 پارامترها:
    - iterable: لیست/تاپل اعداد
    - start (اختیاری): مقدار شروع — پیش‌فرض 0

    📌 برمی‌گردونه: مجموع
    """
    ...

@overload
def sorted(
    iterable: Iterable[T],
    *,
    key: Optional[Callable[[T], Any]] = ...,
    reverse: bool = ...
) -> list: ...
@overload
def sorted(
    iterable: Iterable[T],
    cmp: Callable[[T, T], int],
    *,
    key: Optional[Callable[[T], Any]] = ...,
    reverse: bool = ...
) -> list: ...
def sorted(iterable: Iterable, *args: Any, **kwargs: Any) -> list:
    """
    📌 فرمول رایج:
    sorted([3, 1, 2])                    ← [1, 2, 3]
    sorted([3, 1, 2], reverse=True)      ← [3, 2, 1]
    sorted(contours, key=cv2.contourArea, reverse=True)

    📌 پارامترها:
    - iterable: لیست/تاپل/مجموعه
    - key (اختیاری): تابع کلید برای مرتب‌سازی
    - reverse (اختیاری): True برای نزولی

    📌 نکته: لیست اصلی را تغییر نمی‌دهد (برخلاف list.sort())
    """
    ...

# ============================================================
# enumerate
# ============================================================
def enumerate(iterable: Iterable, start: int = ...) -> Iterable[tuple]:
    """
    📌 فرمول رایج:
    for index, item in enumerate(my_list):
        print(index, item)

    📌 پارامترها:
    - iterable: لیست، تاپل، رشته و ...
    - start (اختیاری): شروع شمارش — پیش‌فرض 0

    📌 برمی‌گردونه: جفت‌های (index, value)
    """
    ...

# ============================================================
# zip
# ============================================================
def zip(*iterables: Iterable) -> Iterable[tuple]:
    """
    📌 فرمول رایج:
    for a, b in zip(list1, list2):
        print(a, b)

    list(zip([1, 2], ["a", "b"]))    ← [(1, 'a'), (2, 'b')]

    📌 نکته: از کوتاه‌ترین لیست پیروی می‌کند
    """
    ...

# ============================================================
# range
# ============================================================
class range:
    @overload
    def __init__(self, stop: int) -> None: ...
    @overload
    def __init__(self, start: int, stop: int, step: int = ...) -> None: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __contains__(self, item: int) -> bool: ...
    def __reversed__(self) -> Any: ...
    def count(self, value: int) -> int: ...
    def index(self, value: int) -> int: ...

# ============================================================
# list / tuple / dict / set (Generic)
# ============================================================
class list(Generic[T]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[T]) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> list[T]: ...
    def __setitem__(self, index: int, value: T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: T) -> bool: ...
    def __add__(self, other: list[T]) -> list[T]: ...
    def __mul__(self, other: int) -> list[T]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: list[T]) -> bool: ...
    def __le__(self, other: list[T]) -> bool: ...
    def __gt__(self, other: list[T]) -> bool: ...
    def __ge__(self, other: list[T]) -> bool: ...
    def __hash__(self) -> None: ...
    def append(self, x: T) -> None: ...
    def extend(self, iterable: Iterable[T]) -> None: ...
    def insert(self, index: int, x: T) -> None: ...
    def remove(self, x: T) -> None: ...
    def pop(self, index: int = ...) -> T: ...
    def clear(self) -> None: ...
    def index(self, x: T) -> int: ...
    def count(self, x: T) -> int: ...
    def sort(
        self, key: Optional[Callable[[T], Any]] = ..., reverse: bool = ...
    ) -> None: ...
    def reverse(self) -> None: ...
    def copy(self) -> list[T]: ...

class tuple(Generic[T]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[T]) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[T, ...]: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: T) -> bool: ...
    def __add__(self, other: tuple[T, ...]) -> tuple[T, ...]: ...
    def __mul__(self, other: int) -> tuple[T, ...]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: tuple[T, ...]) -> bool: ...
    def __le__(self, other: tuple[T, ...]) -> bool: ...
    def __gt__(self, other: tuple[T, ...]) -> bool: ...
    def __ge__(self, other: tuple[T, ...]) -> bool: ...
    def __hash__(self) -> int: ...
    def count(self, x: T) -> int: ...
    def index(self, x: T) -> int: ...

class dict(Generic[K, V]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[tuple[K, V]]) -> None: ...
    @overload
    def __init__(self, **kwargs: V) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, key: K) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __hash__(self) -> None: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...
    def get(self, key: K, default: Optional[V] = ...) -> Optional[V]: ...
    def update(self, other: dict[K, V]) -> None: ...
    def pop(self, key: K, default: Optional[V] = ...) -> Optional[V]: ...
    def popitem(self) -> tuple[K, V]: ...
    def clear(self) -> None: ...
    def copy(self) -> dict[K, V]: ...
    def setdefault(self, key: K, default: Optional[V] = ...) -> Optional[V]: ...

class set(Generic[T]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[T]) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: T) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: set[T]) -> bool: ...
    def __le__(self, other: set[T]) -> bool: ...
    def __gt__(self, other: set[T]) -> bool: ...
    def __ge__(self, other: set[T]) -> bool: ...
    def __or__(self, other: set[T]) -> set[T]: ...
    def __and__(self, other: set[T]) -> set[T]: ...
    def __sub__(self, other: set[T]) -> set[T]: ...
    def __xor__(self, other: set[T]) -> set[T]: ...
    def __hash__(self) -> None: ...
    def add(self, x: T) -> None: ...
    def remove(self, x: T) -> None: ...
    def discard(self, x: T) -> None: ...
    def pop(self) -> T: ...
    def clear(self) -> None: ...
    def union(self, *others: set[T]) -> set[T]: ...
    def intersection(self, *others: set[T]) -> set[T]: ...
    def difference(self, *others: set[T]) -> set[T]: ...
    def issubset(self, other: set[T]) -> bool: ...
    def issuperset(self, other: set[T]) -> bool: ...
    def copy(self) -> set[T]: ...

# ============================================================
# input
# ============================================================
def input(prompt: Optional[str] = ...) -> str:
    """
    📌 فرمول رایج:
    name = input("Enter your name: ")

    📌 پارامترها:
    - prompt (اختیاری): پیام نمایشی

    📌 برمی‌گردونه: رشته — همیشه! (برای عدد باید int/float کنی)
    """
    ...

# ============================================================
# any / all
# ============================================================
def any(iterable: Iterable) -> bool:
    """
    📌 فرمول رایج:
    any([False, False, True])    ← True

    📌 برمی‌گردونه: True اگر حداقل یک عنصر True باشد
    """
    ...

def all(iterable: Iterable) -> bool:
    """
    📌 فرمول رایج:
    all([True, True, True])      ← True
    all([True, False, True])     ← False

    📌 برمی‌گردونه: True اگر همه عناصر True باشند
    """
    ...

# ============================================================
# isinstance
# ============================================================
def isinstance(obj: Any, class_or_tuple: Union[type, tuple]) -> bool:
    """
    📌 فرمول رایج:
    isinstance(5, int)           ← True
    isinstance("hi", str)        ← True
    isinstance(5, (int, float))  ← True

    📌 برمی‌گردونه: True اگر obj از نوع مشخص شده باشد
    """
    ...

# ============================================================
# open
# ============================================================
def open(
    file: Union[str, bytes, int],
    mode: str = ...,
    buffering: int = ...,
    encoding: Optional[str] = ...,
    errors: Optional[str] = ...,
    newline: Optional[str] = ...,
    closefd: bool = ...,
    opener: Optional[Callable] = ...,
) -> Any:
    """
    📌 فرمول رایج:
    with open("file.txt", "r", encoding="utf-8") as f:
        content = f.read()

    📌 پارامترها:
    - file: مسیر فایل
    - mode: 'r' خواندن | 'w' نوشتن | 'a' افزودن | 'rb' باینری
    - encoding: 'utf-8' برای متن فارسی

    📌 نکته: همیشه با with استفاده کن تا فایل خودکار بسته شود
    """
    ...
